### ISSUE TITLE
syntax error or bad assumptions?

### ISSUE THREAD

**Issue by adamphetamine** [ariadar/Zoho-Creator-ChatGPT#1]
![Screenshot 2023-04-25 at 7 06 20 pm](https://user-images.githubusercontent.com/47110465/234229240-e804630f-6eaf-47f1-b93e-fc8a78ff4bfb.png)
I'm getting an error with line 2-

if(input.Text_Input != "" && input.Refine_Input = false && input.Chat_Output == "")

because you're setting up a header map it shouldn't require a ';' at the end of the line, but perhaps I have done something else wrong?
I guess I should ask- what is needed to be set up before this will work?
Should it be a 'function' or a 'workflow'?

**Comment by ariadar** [comment]
A header map requires a ";" in the syntax. See [here](https://www.zoho.com/deluge/help/map-manipulations/create-map.html). 

The sample script is for deployment as a workflow. 

Often ZC will identify a problem citing a particular line number, but the bug could occur anywhere else in the logic that begins from that line number.
